CREATE TABLE IF NOT EXISTS teste(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste(
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(cpf)
);

INSERT INTO teste(cpf, nome)
VALUES('15783232199', 'Tiago Gabay Zagri')

INSERT INTO teste(cpf, nome)
VALUES('15783232199', 'Tiago Gabay Zagri') ON CONFLICT (cpf) DO NOTHING;

UPDATE teste SET nome = 'Tiago dLima' WHERE cpf = '15783232199';

SELECT * FROM teste;
